name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Deploy when the main branch is updated

jobs:
  build:
    runs-on: ubuntu-latest
    environment: VPS_CICD

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker-compose build
          docker tag clio:latest lhernandez0/clio:latest

      # Push Docker image to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image
        run: |
          docker push lhernandez0/clio:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: VPS_CICD

    steps:
      # Deploy to VPS using SSH
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            # Pull the latest Docker image
            docker pull lhernandez0/clio:latest

            # Stop and remove old container if it exists
            docker stop clio || true
            docker rm clio || true

            # Run the new container
            docker run -d --name clio -p 80:8000 lhernandez0/clio:latest
