name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Deploy when the main branch is updated

jobs:
  build:
    runs-on: ubuntu-latest
    environment: VPS_CICD

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d\" -f4)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker-compose build
          docker tag clio_airflow-webserver:latest lhernandez0/clio_airflow-webserver:latest
          docker tag clio_airflow-scheduler:latest lhernandez0/clio_airflow-scheduler:latest
          docker tag clio_airflow-worker:latest lhernandez0/clio_airflow-worker:latest
          docker tag clio_airflow-triggerer:latest lhernandez0/clio_airflow-triggerer:latest
          docker tag clio_airflow-init:latest lhernandez0/clio_airflow-init:latest
          docker tag clio_airflow-cli:latest lhernandez0/clio_airflow-cli:latest
          docker tag clio_flower:latest lhernandez0/clio_flower:latest
          docker tag clio_webserver:latest lhernandez0/clio_webserver:latest

      # Push Docker image to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image
        run: |
          docker push lhernandez0/clio_airflow-webserver:latest
          docker push lhernandez0/clio_airflow-scheduler:latest
          docker push lhernandez0/clio_airflow-worker:latest
          docker push lhernandez0/clio_airflow-triggerer:latest
          docker push lhernandez0/clio_airflow-init:latest
          docker push lhernandez0/clio_airflow-cli:latest
          docker push lhernandez0/clio_flower:latest
          docker push lhernandez0/clio_webserver:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: VPS_CICD

    steps:
      # Deploy to VPS using SSH
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            # Clone the repository if it doesn't already exist
            if [ ! -d "clio" ]; then
              git clone https://github.com/lhernandez0/clio.git
            fi

            # Navigate to the repository directory
            cd clio

            # Fetch the latest changes
            git pull origin main

            # Install Docker Compose if not already installed
            if ! docker-compose --version > /dev/null 2>&1; then
              sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d\" -f4)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Pull the latest Docker images
            docker-compose pull

            # Stop and remove old containers and networks
            docker-compose down

            # Run the new containers
            docker-compose up -d
